version: '3.8'
services:
  taky:
    build:
      context: .
    ports:
      - "8089:8089"
    restart: always
    volumes:
      - "./taky/home:/home/taky"
      - "./taky/etc:/etc/taky"
      - "./taky/var:/var/taky"
